#!/bin/bash
# Install and update software
printf $DIVIDER
printf "INSTALL ET UPDATE\n"
printf "préparation de l'installation.\n"
read -p "Please ENTER to continue "
apt-get -y update -y
apt-get -y upgrade -y
apt install nmap zip dnsutils net-tools tzdata lynx curl git screen -y -f
apt install apache2 -y
a2enmod ssl 
a2ensite default-ssl
systemctl reload apache2 
openssl req $@ -new -x509 -days 3560 -nodes -out /etc/apache2/apache.pem -keyout /etc/apache2/apache.pem
a2enmod rewrite
systemctl reload apache2
cp 000-default.conf /etc/apache2/sites-available/000-default.conf
cp default-ssl.conf  /etc/apache2/sites-available/default-ssl.conf
cp apache2.conf  /etc/apache2/apache2.conf
systemctl reload apache2
chown -R www-data:www-data /home/debian/www
usermod -a -G www-data debian
chmod -R 775 /home/debian/www
apt update
apt install mariadb-server mariadb-client -y
mysql_secure_installation -y
apt install php php-json php-mbstring php-zip php-gd php-xml php-curl php-mysql -y
wget https://files.phpmyadmin.net/phpMyAdmin/5.0.4/phpMyAdmin-5.0.4-all-languages.zip
unzip phpMyAdmin-5.0.4-all-languages  -d /opt
mv -v /opt/phpMyAdmin-5.0.4-all-languages /opt/phpMyAdmin
chown -Rfv www-data:www-data /opt/phpMyAdmin
cp phpmyadmin.conf  /etc/apache2/sites-available/phpmyadmin.conf
cp ports.conf   /etc/apache2/ports.conf 
a2ensite phpmyadmin.conf
systemctl restart apache2
apt install vsftpd -y
cp /etc/vsftpd.conf /etc/vsftpd.bak
rm /etc/vsftpd.conf
cp vsftpd.conf  /etc/vsftpd.conf
touch /var/log/vsftpd.log
service vsftpd restart
curl -O https://wordpress.org/latest.tar.gz
echo "Extracting tarball wordpress..."
tar -zxvf latest.tar.gz
cp -rf wordpress/*  /home/debian/www
chown -R www-data:www-data /home/debian/www/*
rm -R wordpress
cat <<EOF | mysql -u root -p 
GRANT ALL ON *.* TO 'debian1'@'localhost' IDENTIFIED BY 'rooty';
CREATE DATABASE wordpress;
EOF
cp wp-config.php  /home/debian/www/wp-config.php
chmod +x firewall
cp firewall /etc/init.d
/etc/init.d/firewall
update-rc.d firewall defaults
hostname --fqdn > /etc/mailname
apt install postfix -y 
cp main.cf /etc/postfix/main.cf
service postfix restart
apt install mailutils -y
echo "server up" | mail -s "srv web up " you@gmail.com
apt install fail2ban -y
cp jail.local /etc/fail2ban/jail.local
cp apache-wp-login.conf /etc/fail2ban/filter.d/apache-wp-login.conf
fail2ban-client reload






